name: lint

on:
  push:
    branches:
      - master
    paths:
      - '**/*.tsx'
      - '**/*.ts'

  pull_request:
    branches:
      - master
    paths:
      - '**/*.tsx'
      - '**/*.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        make install
        make lint
